# Generated by Django 3.0.4 on 2020-10-18 05:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=100, verbose_name='Nama Produk')),
                ('gambar', models.ImageField(default='default.jpg', upload_to='images', verbose_name='Gambar Produk')),
                ('detail', models.TextField(verbose_name='Detail Produk')),
                ('harga', models.IntegerField(verbose_name='Harga')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dibuat tanggal : ')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Tags', verbose_name='Tags')),
            ],
        ),
    ]
